# Generated by Django 3.0.2 on 2020-02-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_introduction',
            field=models.TextField(default=''),
        ),
    ]
