# Generated by Django 3.0.2 on 2020-03-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
        migrations.AddField(
            model_name='user',
            name='pic_url',
            field=models.TextField(default='', null=True),
        ),
    ]
