# Generated by Django 3.0.2 on 2020-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200301_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.TextField(null=True),
        ),
    ]
