# Generated by Django 3.0.2 on 2020-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200312_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
