# Generated by Django 3.0.7 on 2020-06-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_user_if_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
