# Generated by Django 3.0.2 on 2020-02-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_category_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_introduction',
            field=models.TextField(default=''),
        ),
    ]
