# Generated by Django 3.0.2 on 2020-02-18 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200214_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_content', models.TextField(default='')),
                ('lesson_name', models.CharField(max_length=255)),
                ('lesson_video', models.TextField(default='')),
                ('homework_title', models.CharField(max_length=255)),
                ('homework_description', models.TextField(default='')),
                ('homework_attachment', models.FileField(null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
    ]
