# Generated by Django 3.0.2 on 2020-03-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200225_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='if_compiler',
            field=models.BooleanField(default=False),
        ),
    ]
