# Generated by Django 3.0.2 on 2020-03-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_lesson_if_compiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
