# Generated by Django 3.0.2 on 2020-03-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200313_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_pic',
            field=models.TextField(blank=True, default='https://miro.medium.com/max/3336/1*YMFKP8e6kR9cbM3IKXBtLw.png', null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
