# Generated by Django 3.0.2 on 2020-04-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200317_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
