# Generated by Django 3.0.7 on 2020-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20200622_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='complier_url',
            field=models.TextField(null=True),
        ),
    ]
