# Generated by Django 3.0.7 on 2020-07-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_category_complier_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='homework_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
