# Generated by Django 3.0.7 on 2020-08-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20200803_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='if_share',
            field=models.BooleanField(default=False),
        ),
    ]
