# Generated by Django 3.0.7 on 2020-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_note_if_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='if_share',
            field=models.BooleanField(default=False),
        ),
    ]
