# Generated by Django 3.0.2 on 2020-08-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_homework_if_share'),
        ('group', '0005_group_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_num',
            field=models.CharField(default='', max_length=255),
        ),
    ]
