# Generated by Django 3.0.2 on 2020-08-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20200830_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_num',
            field=models.IntegerField(null=True),
        ),
    ]
