# Generated by Django 3.0.2 on 2020-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20200831_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='project_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
